[package]
name = "ewrs"
version = "0.6.2"
authors = ["Iku Iwasa <iku.iwasa@gmail.com>"]
build = "build.rs"
edition = "2024"

[target.'cfg(unix)'.dependencies]
libc = "*"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62.2", features = [
  "Win32_System_ProcessStatus",
  "Win32_System_Threading",
  "Win32_UI_WindowsAndMessaging",
]}

[target.'cfg(windows)'.build-dependencies]
winres = "*"

[[bin]]
name = "ew"
path = "src/main.rs"

[[bin]]
name = "ew-w"
path = "src/main-w.rs"

[dependencies]
dirs = "^7.0.0"

[features]
default = ["emacs27"]
emacs27 = []
